name: link-to-checklist

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  add-review-checklist:
    if : ${{ github.event_name == 'pull_request_target' && github.event.action == 'opened' && startsWith(github.event.pull_request.title, 'ingestion') == true}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Print event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Starts with ingestion: ${{ startsWith(github.event.pull_request.title, 'ingestion') }}"
      - name: Add review checklist
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            console.log('Reading checklist file...');
            const review_checklist = fs.readFileSync('.github/ingestion-review-checklist.md', 'utf8');
            const old_description = context.payload.pull_request.body || '';
            console.log('Old description:', ${ old_description });
            if (!old_description.trim()) {
              await github.rest.pulls.update({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: review_checklist,
              });
              console.log('Pull request description was empty. Updated with review checklist.');
            } else {
              await github.rest.pulls.update({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: context.payload.pull_request.body + review_checklist,
              });
              console.log('Pull request description was not empty. Appended review checklist.');
            }
